
GET http://localhost:3001/api/serviceinfo HTTP/1.1

###

POST http://localhost:3001/api/ticket HTTP/1.1
content-type: application/json

{
    "serviceID": 100
}
###

PUT http://localhost:3001/api/next HTTP/1.1
content-type: application/json

{
    "counterId": 0
}

###

GET http://localhost:3001/api/stats HTTP/1.1
